// Autogenerated from Pigeon (v17.1.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.medallia.medallia_dxa;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class StartScreenMessage {
    private @NonNull String screenName;

    public @NonNull String getScreenName() {
      return screenName;
    }

    public void setScreenName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenName\" is null.");
      }
      this.screenName = setterArg;
    }

    private @NonNull Long screenId;

    public @NonNull Long getScreenId() {
      return screenId;
    }

    public void setScreenId(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenId\" is null.");
      }
      this.screenId = setterArg;
    }

    private @NonNull Long startTime;

    public @NonNull Long getStartTime() {
      return startTime;
    }

    public void setStartTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"startTime\" is null.");
      }
      this.startTime = setterArg;
    }

    private @NonNull Boolean isBackground;

    public @NonNull Boolean getIsBackground() {
      return isBackground;
    }

    public void setIsBackground(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isBackground\" is null.");
      }
      this.isBackground = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    StartScreenMessage() {}

    public static final class Builder {

      private @Nullable String screenName;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenName(@NonNull String setterArg) {
        this.screenName = setterArg;
        return this;
      }

      private @Nullable Long screenId;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenId(@NonNull Long setterArg) {
        this.screenId = setterArg;
        return this;
      }

      private @Nullable Long startTime;

      @CanIgnoreReturnValue
      public @NonNull Builder setStartTime(@NonNull Long setterArg) {
        this.startTime = setterArg;
        return this;
      }

      private @Nullable Boolean isBackground;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsBackground(@NonNull Boolean setterArg) {
        this.isBackground = setterArg;
        return this;
      }

      public @NonNull StartScreenMessage build() {
        StartScreenMessage pigeonReturn = new StartScreenMessage();
        pigeonReturn.setScreenName(screenName);
        pigeonReturn.setScreenId(screenId);
        pigeonReturn.setStartTime(startTime);
        pigeonReturn.setIsBackground(isBackground);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(4);
      toListResult.add(screenName);
      toListResult.add(screenId);
      toListResult.add(startTime);
      toListResult.add(isBackground);
      return toListResult;
    }

    static @NonNull StartScreenMessage fromList(@NonNull ArrayList<Object> list) {
      StartScreenMessage pigeonResult = new StartScreenMessage();
      Object screenName = list.get(0);
      pigeonResult.setScreenName((String) screenName);
      Object screenId = list.get(1);
      pigeonResult.setScreenId((screenId == null) ? null : ((screenId instanceof Integer) ? (Integer) screenId : (Long) screenId));
      Object startTime = list.get(2);
      pigeonResult.setStartTime((startTime == null) ? null : ((startTime instanceof Integer) ? (Integer) startTime : (Long) startTime));
      Object isBackground = list.get(3);
      pigeonResult.setIsBackground((Boolean) isBackground);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class EndScreenMessage {
    private @NonNull String screenName;

    public @NonNull String getScreenName() {
      return screenName;
    }

    public void setScreenName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenName\" is null.");
      }
      this.screenName = setterArg;
    }

    private @NonNull Long screenId;

    public @NonNull Long getScreenId() {
      return screenId;
    }

    public void setScreenId(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenId\" is null.");
      }
      this.screenId = setterArg;
    }

    private @NonNull Long endTime;

    public @NonNull Long getEndTime() {
      return endTime;
    }

    public void setEndTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"endTime\" is null.");
      }
      this.endTime = setterArg;
    }

    private @NonNull Long screenRecordingEndTime;

    public @NonNull Long getScreenRecordingEndTime() {
      return screenRecordingEndTime;
    }

    public void setScreenRecordingEndTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenRecordingEndTime\" is null.");
      }
      this.screenRecordingEndTime = setterArg;
    }

    private @NonNull Boolean isBackground;

    public @NonNull Boolean getIsBackground() {
      return isBackground;
    }

    public void setIsBackground(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isBackground\" is null.");
      }
      this.isBackground = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    EndScreenMessage() {}

    public static final class Builder {

      private @Nullable String screenName;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenName(@NonNull String setterArg) {
        this.screenName = setterArg;
        return this;
      }

      private @Nullable Long screenId;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenId(@NonNull Long setterArg) {
        this.screenId = setterArg;
        return this;
      }

      private @Nullable Long endTime;

      @CanIgnoreReturnValue
      public @NonNull Builder setEndTime(@NonNull Long setterArg) {
        this.endTime = setterArg;
        return this;
      }

      private @Nullable Long screenRecordingEndTime;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenRecordingEndTime(@NonNull Long setterArg) {
        this.screenRecordingEndTime = setterArg;
        return this;
      }

      private @Nullable Boolean isBackground;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsBackground(@NonNull Boolean setterArg) {
        this.isBackground = setterArg;
        return this;
      }

      public @NonNull EndScreenMessage build() {
        EndScreenMessage pigeonReturn = new EndScreenMessage();
        pigeonReturn.setScreenName(screenName);
        pigeonReturn.setScreenId(screenId);
        pigeonReturn.setEndTime(endTime);
        pigeonReturn.setScreenRecordingEndTime(screenRecordingEndTime);
        pigeonReturn.setIsBackground(isBackground);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(5);
      toListResult.add(screenName);
      toListResult.add(screenId);
      toListResult.add(endTime);
      toListResult.add(screenRecordingEndTime);
      toListResult.add(isBackground);
      return toListResult;
    }

    static @NonNull EndScreenMessage fromList(@NonNull ArrayList<Object> list) {
      EndScreenMessage pigeonResult = new EndScreenMessage();
      Object screenName = list.get(0);
      pigeonResult.setScreenName((String) screenName);
      Object screenId = list.get(1);
      pigeonResult.setScreenId((screenId == null) ? null : ((screenId instanceof Integer) ? (Integer) screenId : (Long) screenId));
      Object endTime = list.get(2);
      pigeonResult.setEndTime((endTime == null) ? null : ((endTime instanceof Integer) ? (Integer) endTime : (Long) endTime));
      Object screenRecordingEndTime = list.get(3);
      pigeonResult.setScreenRecordingEndTime((screenRecordingEndTime == null) ? null : ((screenRecordingEndTime instanceof Integer) ? (Integer) screenRecordingEndTime : (Long) screenRecordingEndTime));
      Object isBackground = list.get(4);
      pigeonResult.setIsBackground((Boolean) isBackground);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SessionMessage {
    private @NonNull Long account;

    public @NonNull Long getAccount() {
      return account;
    }

    public void setAccount(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"account\" is null.");
      }
      this.account = setterArg;
    }

    private @NonNull Long property;

    public @NonNull Long getProperty() {
      return property;
    }

    public void setProperty(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"property\" is null.");
      }
      this.property = setterArg;
    }

    private @NonNull Long consents;

    public @NonNull Long getConsents() {
      return consents;
    }

    public void setConsents(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"consents\" is null.");
      }
      this.consents = setterArg;
    }

    private @NonNull String version;

    public @NonNull String getVersion() {
      return version;
    }

    public void setVersion(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"version\" is null.");
      }
      this.version = setterArg;
    }

    private @NonNull Boolean crashReporterEnabled;

    public @NonNull Boolean getCrashReporterEnabled() {
      return crashReporterEnabled;
    }

    public void setCrashReporterEnabled(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"crashReporterEnabled\" is null.");
      }
      this.crashReporterEnabled = setterArg;
    }

    private @NonNull Boolean mobileDataEnabled;

    public @NonNull Boolean getMobileDataEnabled() {
      return mobileDataEnabled;
    }

    public void setMobileDataEnabled(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"mobileDataEnabled\" is null.");
      }
      this.mobileDataEnabled = setterArg;
    }

    private @NonNull Boolean enhancedLogs;

    public @NonNull Boolean getEnhancedLogs() {
      return enhancedLogs;
    }

    public void setEnhancedLogs(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"enhancedLogs\" is null.");
      }
      this.enhancedLogs = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    SessionMessage() {}

    public static final class Builder {

      private @Nullable Long account;

      @CanIgnoreReturnValue
      public @NonNull Builder setAccount(@NonNull Long setterArg) {
        this.account = setterArg;
        return this;
      }

      private @Nullable Long property;

      @CanIgnoreReturnValue
      public @NonNull Builder setProperty(@NonNull Long setterArg) {
        this.property = setterArg;
        return this;
      }

      private @Nullable Long consents;

      @CanIgnoreReturnValue
      public @NonNull Builder setConsents(@NonNull Long setterArg) {
        this.consents = setterArg;
        return this;
      }

      private @Nullable String version;

      @CanIgnoreReturnValue
      public @NonNull Builder setVersion(@NonNull String setterArg) {
        this.version = setterArg;
        return this;
      }

      private @Nullable Boolean crashReporterEnabled;

      @CanIgnoreReturnValue
      public @NonNull Builder setCrashReporterEnabled(@NonNull Boolean setterArg) {
        this.crashReporterEnabled = setterArg;
        return this;
      }

      private @Nullable Boolean mobileDataEnabled;

      @CanIgnoreReturnValue
      public @NonNull Builder setMobileDataEnabled(@NonNull Boolean setterArg) {
        this.mobileDataEnabled = setterArg;
        return this;
      }

      private @Nullable Boolean enhancedLogs;

      @CanIgnoreReturnValue
      public @NonNull Builder setEnhancedLogs(@NonNull Boolean setterArg) {
        this.enhancedLogs = setterArg;
        return this;
      }

      public @NonNull SessionMessage build() {
        SessionMessage pigeonReturn = new SessionMessage();
        pigeonReturn.setAccount(account);
        pigeonReturn.setProperty(property);
        pigeonReturn.setConsents(consents);
        pigeonReturn.setVersion(version);
        pigeonReturn.setCrashReporterEnabled(crashReporterEnabled);
        pigeonReturn.setMobileDataEnabled(mobileDataEnabled);
        pigeonReturn.setEnhancedLogs(enhancedLogs);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(7);
      toListResult.add(account);
      toListResult.add(property);
      toListResult.add(consents);
      toListResult.add(version);
      toListResult.add(crashReporterEnabled);
      toListResult.add(mobileDataEnabled);
      toListResult.add(enhancedLogs);
      return toListResult;
    }

    static @NonNull SessionMessage fromList(@NonNull ArrayList<Object> list) {
      SessionMessage pigeonResult = new SessionMessage();
      Object account = list.get(0);
      pigeonResult.setAccount((account == null) ? null : ((account instanceof Integer) ? (Integer) account : (Long) account));
      Object property = list.get(1);
      pigeonResult.setProperty((property == null) ? null : ((property instanceof Integer) ? (Integer) property : (Long) property));
      Object consents = list.get(2);
      pigeonResult.setConsents((consents == null) ? null : ((consents instanceof Integer) ? (Integer) consents : (Long) consents));
      Object version = list.get(3);
      pigeonResult.setVersion((String) version);
      Object crashReporterEnabled = list.get(4);
      pigeonResult.setCrashReporterEnabled((Boolean) crashReporterEnabled);
      Object mobileDataEnabled = list.get(5);
      pigeonResult.setMobileDataEnabled((Boolean) mobileDataEnabled);
      Object enhancedLogs = list.get(6);
      pigeonResult.setEnhancedLogs((Boolean) enhancedLogs);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ScreenshotMessage {
    private @NonNull byte[] screenshotData;

    public @NonNull byte[] getScreenshotData() {
      return screenshotData;
    }

    public void setScreenshotData(@NonNull byte[] setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenshotData\" is null.");
      }
      this.screenshotData = setterArg;
    }

    private @NonNull Long screenId;

    public @NonNull Long getScreenId() {
      return screenId;
    }

    public void setScreenId(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenId\" is null.");
      }
      this.screenId = setterArg;
    }

    private @NonNull String screenName;

    public @NonNull String getScreenName() {
      return screenName;
    }

    public void setScreenName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"screenName\" is null.");
      }
      this.screenName = setterArg;
    }

    private @NonNull Long startFocusTime;

    public @NonNull Long getStartFocusTime() {
      return startFocusTime;
    }

    public void setStartFocusTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"startFocusTime\" is null.");
      }
      this.startFocusTime = setterArg;
    }

    private @NonNull Boolean isPlaceholder;

    public @NonNull Boolean getIsPlaceholder() {
      return isPlaceholder;
    }

    public void setIsPlaceholder(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isPlaceholder\" is null.");
      }
      this.isPlaceholder = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ScreenshotMessage() {}

    public static final class Builder {

      private @Nullable byte[] screenshotData;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenshotData(@NonNull byte[] setterArg) {
        this.screenshotData = setterArg;
        return this;
      }

      private @Nullable Long screenId;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenId(@NonNull Long setterArg) {
        this.screenId = setterArg;
        return this;
      }

      private @Nullable String screenName;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreenName(@NonNull String setterArg) {
        this.screenName = setterArg;
        return this;
      }

      private @Nullable Long startFocusTime;

      @CanIgnoreReturnValue
      public @NonNull Builder setStartFocusTime(@NonNull Long setterArg) {
        this.startFocusTime = setterArg;
        return this;
      }

      private @Nullable Boolean isPlaceholder;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsPlaceholder(@NonNull Boolean setterArg) {
        this.isPlaceholder = setterArg;
        return this;
      }

      public @NonNull ScreenshotMessage build() {
        ScreenshotMessage pigeonReturn = new ScreenshotMessage();
        pigeonReturn.setScreenshotData(screenshotData);
        pigeonReturn.setScreenId(screenId);
        pigeonReturn.setScreenName(screenName);
        pigeonReturn.setStartFocusTime(startFocusTime);
        pigeonReturn.setIsPlaceholder(isPlaceholder);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(5);
      toListResult.add(screenshotData);
      toListResult.add(screenId);
      toListResult.add(screenName);
      toListResult.add(startFocusTime);
      toListResult.add(isPlaceholder);
      return toListResult;
    }

    static @NonNull ScreenshotMessage fromList(@NonNull ArrayList<Object> list) {
      ScreenshotMessage pigeonResult = new ScreenshotMessage();
      Object screenshotData = list.get(0);
      pigeonResult.setScreenshotData((byte[]) screenshotData);
      Object screenId = list.get(1);
      pigeonResult.setScreenId((screenId == null) ? null : ((screenId instanceof Integer) ? (Integer) screenId : (Long) screenId));
      Object screenName = list.get(2);
      pigeonResult.setScreenName((String) screenName);
      Object startFocusTime = list.get(3);
      pigeonResult.setStartFocusTime((startFocusTime == null) ? null : ((startFocusTime instanceof Integer) ? (Integer) startFocusTime : (Long) startFocusTime));
      Object isPlaceholder = list.get(4);
      pigeonResult.setIsPlaceholder((Boolean) isPlaceholder);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DimensionStringMessage {
    private @NonNull String dimensionName;

    public @NonNull String getDimensionName() {
      return dimensionName;
    }

    public void setDimensionName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dimensionName\" is null.");
      }
      this.dimensionName = setterArg;
    }

    private @NonNull String value;

    public @NonNull String getValue() {
      return value;
    }

    public void setValue(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"value\" is null.");
      }
      this.value = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DimensionStringMessage() {}

    public static final class Builder {

      private @Nullable String dimensionName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDimensionName(@NonNull String setterArg) {
        this.dimensionName = setterArg;
        return this;
      }

      private @Nullable String value;

      @CanIgnoreReturnValue
      public @NonNull Builder setValue(@NonNull String setterArg) {
        this.value = setterArg;
        return this;
      }

      public @NonNull DimensionStringMessage build() {
        DimensionStringMessage pigeonReturn = new DimensionStringMessage();
        pigeonReturn.setDimensionName(dimensionName);
        pigeonReturn.setValue(value);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(dimensionName);
      toListResult.add(value);
      return toListResult;
    }

    static @NonNull DimensionStringMessage fromList(@NonNull ArrayList<Object> list) {
      DimensionStringMessage pigeonResult = new DimensionStringMessage();
      Object dimensionName = list.get(0);
      pigeonResult.setDimensionName((String) dimensionName);
      Object value = list.get(1);
      pigeonResult.setValue((String) value);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DimensionNumberMessage {
    private @NonNull String dimensionName;

    public @NonNull String getDimensionName() {
      return dimensionName;
    }

    public void setDimensionName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dimensionName\" is null.");
      }
      this.dimensionName = setterArg;
    }

    private @NonNull Double value;

    public @NonNull Double getValue() {
      return value;
    }

    public void setValue(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"value\" is null.");
      }
      this.value = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DimensionNumberMessage() {}

    public static final class Builder {

      private @Nullable String dimensionName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDimensionName(@NonNull String setterArg) {
        this.dimensionName = setterArg;
        return this;
      }

      private @Nullable Double value;

      @CanIgnoreReturnValue
      public @NonNull Builder setValue(@NonNull Double setterArg) {
        this.value = setterArg;
        return this;
      }

      public @NonNull DimensionNumberMessage build() {
        DimensionNumberMessage pigeonReturn = new DimensionNumberMessage();
        pigeonReturn.setDimensionName(dimensionName);
        pigeonReturn.setValue(value);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(dimensionName);
      toListResult.add(value);
      return toListResult;
    }

    static @NonNull DimensionNumberMessage fromList(@NonNull ArrayList<Object> list) {
      DimensionNumberMessage pigeonResult = new DimensionNumberMessage();
      Object dimensionName = list.get(0);
      pigeonResult.setDimensionName((String) dimensionName);
      Object value = list.get(1);
      pigeonResult.setValue((Double) value);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DimensionBoolMessage {
    private @NonNull String dimensionName;

    public @NonNull String getDimensionName() {
      return dimensionName;
    }

    public void setDimensionName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dimensionName\" is null.");
      }
      this.dimensionName = setterArg;
    }

    private @NonNull Boolean value;

    public @NonNull Boolean getValue() {
      return value;
    }

    public void setValue(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"value\" is null.");
      }
      this.value = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DimensionBoolMessage() {}

    public static final class Builder {

      private @Nullable String dimensionName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDimensionName(@NonNull String setterArg) {
        this.dimensionName = setterArg;
        return this;
      }

      private @Nullable Boolean value;

      @CanIgnoreReturnValue
      public @NonNull Builder setValue(@NonNull Boolean setterArg) {
        this.value = setterArg;
        return this;
      }

      public @NonNull DimensionBoolMessage build() {
        DimensionBoolMessage pigeonReturn = new DimensionBoolMessage();
        pigeonReturn.setDimensionName(dimensionName);
        pigeonReturn.setValue(value);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(dimensionName);
      toListResult.add(value);
      return toListResult;
    }

    static @NonNull DimensionBoolMessage fromList(@NonNull ArrayList<Object> list) {
      DimensionBoolMessage pigeonResult = new DimensionBoolMessage();
      Object dimensionName = list.get(0);
      pigeonResult.setDimensionName((String) dimensionName);
      Object value = list.get(1);
      pigeonResult.setValue((Boolean) value);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class GoalMessage {
    private @NonNull String goal;

    public @NonNull String getGoal() {
      return goal;
    }

    public void setGoal(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"goal\" is null.");
      }
      this.goal = setterArg;
    }

    private @Nullable Double value;

    public @Nullable Double getValue() {
      return value;
    }

    public void setValue(@Nullable Double setterArg) {
      this.value = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    GoalMessage() {}

    public static final class Builder {

      private @Nullable String goal;

      @CanIgnoreReturnValue
      public @NonNull Builder setGoal(@NonNull String setterArg) {
        this.goal = setterArg;
        return this;
      }

      private @Nullable Double value;

      @CanIgnoreReturnValue
      public @NonNull Builder setValue(@Nullable Double setterArg) {
        this.value = setterArg;
        return this;
      }

      public @NonNull GoalMessage build() {
        GoalMessage pigeonReturn = new GoalMessage();
        pigeonReturn.setGoal(goal);
        pigeonReturn.setValue(value);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(goal);
      toListResult.add(value);
      return toListResult;
    }

    static @NonNull GoalMessage fromList(@NonNull ArrayList<Object> list) {
      GoalMessage pigeonResult = new GoalMessage();
      Object goal = list.get(0);
      pigeonResult.setGoal((String) goal);
      Object value = list.get(1);
      pigeonResult.setValue((Double) value);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LiveConfigurationPigeon {
    private @Nullable Boolean overrideUserConfig;

    public @Nullable Boolean getOverrideUserConfig() {
      return overrideUserConfig;
    }

    public void setOverrideUserConfig(@Nullable Boolean setterArg) {
      this.overrideUserConfig = setterArg;
    }

    private @Nullable List<String> blockedFlutterSDKVersions;

    public @Nullable List<String> getBlockedFlutterSDKVersions() {
      return blockedFlutterSDKVersions;
    }

    public void setBlockedFlutterSDKVersions(@Nullable List<String> setterArg) {
      this.blockedFlutterSDKVersions = setterArg;
    }

    private @Nullable List<String> blockedFlutterAppVersions;

    public @Nullable List<String> getBlockedFlutterAppVersions() {
      return blockedFlutterAppVersions;
    }

    public void setBlockedFlutterAppVersions(@Nullable List<String> setterArg) {
      this.blockedFlutterAppVersions = setterArg;
    }

    private @Nullable String maskingColor;

    public @Nullable String getMaskingColor() {
      return maskingColor;
    }

    public void setMaskingColor(@Nullable String setterArg) {
      this.maskingColor = setterArg;
    }

    private @Nullable Boolean showLocalLogs;

    public @Nullable Boolean getShowLocalLogs() {
      return showLocalLogs;
    }

    public void setShowLocalLogs(@Nullable Boolean setterArg) {
      this.showLocalLogs = setterArg;
    }

    private @Nullable Boolean allowLocalLogs;

    public @Nullable Boolean getAllowLocalLogs() {
      return allowLocalLogs;
    }

    public void setAllowLocalLogs(@Nullable Boolean setterArg) {
      this.allowLocalLogs = setterArg;
    }

    private @Nullable Long imageQualityType;

    public @Nullable Long getImageQualityType() {
      return imageQualityType;
    }

    public void setImageQualityType(@Nullable Long setterArg) {
      this.imageQualityType = setterArg;
    }

    private @Nullable Long videoQualityType;

    public @Nullable Long getVideoQualityType() {
      return videoQualityType;
    }

    public void setVideoQualityType(@Nullable Long setterArg) {
      this.videoQualityType = setterArg;
    }

    private @Nullable List<String> disableScreenTracking;

    public @Nullable List<String> getDisableScreenTracking() {
      return disableScreenTracking;
    }

    public void setDisableScreenTracking(@Nullable List<String> setterArg) {
      this.disableScreenTracking = setterArg;
    }

    private @Nullable List<String> screensMasking;

    public @Nullable List<String> getScreensMasking() {
      return screensMasking;
    }

    public void setScreensMasking(@Nullable List<String> setterArg) {
      this.screensMasking = setterArg;
    }

    private @Nullable String appVersion;

    public @Nullable String getAppVersion() {
      return appVersion;
    }

    public void setAppVersion(@Nullable String setterArg) {
      this.appVersion = setterArg;
    }

    public static final class Builder {

      private @Nullable Boolean overrideUserConfig;

      @CanIgnoreReturnValue
      public @NonNull Builder setOverrideUserConfig(@Nullable Boolean setterArg) {
        this.overrideUserConfig = setterArg;
        return this;
      }

      private @Nullable List<String> blockedFlutterSDKVersions;

      @CanIgnoreReturnValue
      public @NonNull Builder setBlockedFlutterSDKVersions(@Nullable List<String> setterArg) {
        this.blockedFlutterSDKVersions = setterArg;
        return this;
      }

      private @Nullable List<String> blockedFlutterAppVersions;

      @CanIgnoreReturnValue
      public @NonNull Builder setBlockedFlutterAppVersions(@Nullable List<String> setterArg) {
        this.blockedFlutterAppVersions = setterArg;
        return this;
      }

      private @Nullable String maskingColor;

      @CanIgnoreReturnValue
      public @NonNull Builder setMaskingColor(@Nullable String setterArg) {
        this.maskingColor = setterArg;
        return this;
      }

      private @Nullable Boolean showLocalLogs;

      @CanIgnoreReturnValue
      public @NonNull Builder setShowLocalLogs(@Nullable Boolean setterArg) {
        this.showLocalLogs = setterArg;
        return this;
      }

      private @Nullable Boolean allowLocalLogs;

      @CanIgnoreReturnValue
      public @NonNull Builder setAllowLocalLogs(@Nullable Boolean setterArg) {
        this.allowLocalLogs = setterArg;
        return this;
      }

      private @Nullable Long imageQualityType;

      @CanIgnoreReturnValue
      public @NonNull Builder setImageQualityType(@Nullable Long setterArg) {
        this.imageQualityType = setterArg;
        return this;
      }

      private @Nullable Long videoQualityType;

      @CanIgnoreReturnValue
      public @NonNull Builder setVideoQualityType(@Nullable Long setterArg) {
        this.videoQualityType = setterArg;
        return this;
      }

      private @Nullable List<String> disableScreenTracking;

      @CanIgnoreReturnValue
      public @NonNull Builder setDisableScreenTracking(@Nullable List<String> setterArg) {
        this.disableScreenTracking = setterArg;
        return this;
      }

      private @Nullable List<String> screensMasking;

      @CanIgnoreReturnValue
      public @NonNull Builder setScreensMasking(@Nullable List<String> setterArg) {
        this.screensMasking = setterArg;
        return this;
      }

      private @Nullable String appVersion;

      @CanIgnoreReturnValue
      public @NonNull Builder setAppVersion(@Nullable String setterArg) {
        this.appVersion = setterArg;
        return this;
      }

      public @NonNull LiveConfigurationPigeon build() {
        LiveConfigurationPigeon pigeonReturn = new LiveConfigurationPigeon();
        pigeonReturn.setOverrideUserConfig(overrideUserConfig);
        pigeonReturn.setBlockedFlutterSDKVersions(blockedFlutterSDKVersions);
        pigeonReturn.setBlockedFlutterAppVersions(blockedFlutterAppVersions);
        pigeonReturn.setMaskingColor(maskingColor);
        pigeonReturn.setShowLocalLogs(showLocalLogs);
        pigeonReturn.setAllowLocalLogs(allowLocalLogs);
        pigeonReturn.setImageQualityType(imageQualityType);
        pigeonReturn.setVideoQualityType(videoQualityType);
        pigeonReturn.setDisableScreenTracking(disableScreenTracking);
        pigeonReturn.setScreensMasking(screensMasking);
        pigeonReturn.setAppVersion(appVersion);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(11);
      toListResult.add(overrideUserConfig);
      toListResult.add(blockedFlutterSDKVersions);
      toListResult.add(blockedFlutterAppVersions);
      toListResult.add(maskingColor);
      toListResult.add(showLocalLogs);
      toListResult.add(allowLocalLogs);
      toListResult.add(imageQualityType);
      toListResult.add(videoQualityType);
      toListResult.add(disableScreenTracking);
      toListResult.add(screensMasking);
      toListResult.add(appVersion);
      return toListResult;
    }

    static @NonNull LiveConfigurationPigeon fromList(@NonNull ArrayList<Object> list) {
      LiveConfigurationPigeon pigeonResult = new LiveConfigurationPigeon();
      Object overrideUserConfig = list.get(0);
      pigeonResult.setOverrideUserConfig((Boolean) overrideUserConfig);
      Object blockedFlutterSDKVersions = list.get(1);
      pigeonResult.setBlockedFlutterSDKVersions((List<String>) blockedFlutterSDKVersions);
      Object blockedFlutterAppVersions = list.get(2);
      pigeonResult.setBlockedFlutterAppVersions((List<String>) blockedFlutterAppVersions);
      Object maskingColor = list.get(3);
      pigeonResult.setMaskingColor((String) maskingColor);
      Object showLocalLogs = list.get(4);
      pigeonResult.setShowLocalLogs((Boolean) showLocalLogs);
      Object allowLocalLogs = list.get(5);
      pigeonResult.setAllowLocalLogs((Boolean) allowLocalLogs);
      Object imageQualityType = list.get(6);
      pigeonResult.setImageQualityType((imageQualityType == null) ? null : ((imageQualityType instanceof Integer) ? (Integer) imageQualityType : (Long) imageQualityType));
      Object videoQualityType = list.get(7);
      pigeonResult.setVideoQualityType((videoQualityType == null) ? null : ((videoQualityType instanceof Integer) ? (Integer) videoQualityType : (Long) videoQualityType));
      Object disableScreenTracking = list.get(8);
      pigeonResult.setDisableScreenTracking((List<String>) disableScreenTracking);
      Object screensMasking = list.get(9);
      pigeonResult.setScreensMasking((List<String>) screensMasking);
      Object appVersion = list.get(10);
      pigeonResult.setAppVersion((String) appVersion);
      return pigeonResult;
    }
  }

  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }

  private static class MedalliaDxaNativeApiCodec extends StandardMessageCodec {
    public static final MedalliaDxaNativeApiCodec INSTANCE = new MedalliaDxaNativeApiCodec();

    private MedalliaDxaNativeApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return DimensionBoolMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 129:
          return DimensionNumberMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return DimensionStringMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return EndScreenMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return GoalMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return LiveConfigurationPigeon.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return ScreenshotMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 135:
          return SessionMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 136:
          return StartScreenMessage.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof DimensionBoolMessage) {
        stream.write(128);
        writeValue(stream, ((DimensionBoolMessage) value).toList());
      } else if (value instanceof DimensionNumberMessage) {
        stream.write(129);
        writeValue(stream, ((DimensionNumberMessage) value).toList());
      } else if (value instanceof DimensionStringMessage) {
        stream.write(130);
        writeValue(stream, ((DimensionStringMessage) value).toList());
      } else if (value instanceof EndScreenMessage) {
        stream.write(131);
        writeValue(stream, ((EndScreenMessage) value).toList());
      } else if (value instanceof GoalMessage) {
        stream.write(132);
        writeValue(stream, ((GoalMessage) value).toList());
      } else if (value instanceof LiveConfigurationPigeon) {
        stream.write(133);
        writeValue(stream, ((LiveConfigurationPigeon) value).toList());
      } else if (value instanceof ScreenshotMessage) {
        stream.write(134);
        writeValue(stream, ((ScreenshotMessage) value).toList());
      } else if (value instanceof SessionMessage) {
        stream.write(135);
        writeValue(stream, ((SessionMessage) value).toList());
      } else if (value instanceof StartScreenMessage) {
        stream.write(136);
        writeValue(stream, ((StartScreenMessage) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface MedalliaDxaNativeApi {

    void initialize(@NonNull SessionMessage msg, @NonNull Result<LiveConfigurationPigeon> result);

    void startScreen(@NonNull StartScreenMessage msg, @NonNull VoidResult result);

    void endScreen(@NonNull EndScreenMessage msg, @NonNull VoidResult result);

    void setConsents(@NonNull Long value);

    void saveScreenshot(@NonNull ScreenshotMessage msg, @NonNull VoidResult result);

    void sendDimensionWithString(@NonNull DimensionStringMessage msg);

    void sendDimensionWithNumber(@NonNull DimensionNumberMessage msg);

    void sendDimensionWithBool(@NonNull DimensionBoolMessage msg);

    void sendGoal(@NonNull GoalMessage msg);

    void sendError(@NonNull String errorMessage);

    void sendDataOverWifiOnly(@NonNull Boolean value);

    void sendHttpError(@NonNull Long msg);

    void sendImageQuality(@NonNull Long imageQuality);

    void setRetention(@NonNull Boolean value);

    void saveLog(@NonNull String log);

    void getWebViewProperties(@NonNull Result<String> result);

    void getSessionId(@NonNull Result<String> result);

    void getSessionUrl(@NonNull Result<String> result);

    /** The codec used by MedalliaDxaNativeApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return MedalliaDxaNativeApiCodec.INSTANCE;
    }
    /**Sets up an instance of `MedalliaDxaNativeApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable MedalliaDxaNativeApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.initialize", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                SessionMessage msgArg = (SessionMessage) args.get(0);
                Result<LiveConfigurationPigeon> resultCallback =
                    new Result<LiveConfigurationPigeon>() {
                      public void success(LiveConfigurationPigeon result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.initialize(msgArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.startScreen", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                StartScreenMessage msgArg = (StartScreenMessage) args.get(0);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.startScreen(msgArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.endScreen", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                EndScreenMessage msgArg = (EndScreenMessage) args.get(0);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.endScreen(msgArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.setConsents", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number valueArg = (Number) args.get(0);
                try {
                  api.setConsents((valueArg == null) ? null : valueArg.longValue());
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.saveScreenshot", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ScreenshotMessage msgArg = (ScreenshotMessage) args.get(0);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.saveScreenshot(msgArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendDimensionWithString", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                DimensionStringMessage msgArg = (DimensionStringMessage) args.get(0);
                try {
                  api.sendDimensionWithString(msgArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendDimensionWithNumber", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                DimensionNumberMessage msgArg = (DimensionNumberMessage) args.get(0);
                try {
                  api.sendDimensionWithNumber(msgArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendDimensionWithBool", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                DimensionBoolMessage msgArg = (DimensionBoolMessage) args.get(0);
                try {
                  api.sendDimensionWithBool(msgArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendGoal", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                GoalMessage msgArg = (GoalMessage) args.get(0);
                try {
                  api.sendGoal(msgArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendError", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String errorMessageArg = (String) args.get(0);
                try {
                  api.sendError(errorMessageArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendDataOverWifiOnly", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Boolean valueArg = (Boolean) args.get(0);
                try {
                  api.sendDataOverWifiOnly(valueArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendHttpError", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number msgArg = (Number) args.get(0);
                try {
                  api.sendHttpError((msgArg == null) ? null : msgArg.longValue());
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.sendImageQuality", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Number imageQualityArg = (Number) args.get(0);
                try {
                  api.sendImageQuality((imageQualityArg == null) ? null : imageQualityArg.longValue());
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.setRetention", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Boolean valueArg = (Boolean) args.get(0);
                try {
                  api.setRetention(valueArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.saveLog", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String logArg = (String) args.get(0);
                try {
                  api.saveLog(logArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.getWebViewProperties", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getWebViewProperties(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.getSessionId", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getSessionId(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.medallia_dxa.MedalliaDxaNativeApi.getSessionUrl", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getSessionUrl(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
